### PR TITLE
Editorials to address Alvaro's comments

### PR DESCRIPTION
**Pull request by pthubert**

### CODE REVIEW

**Review by weiyuehua — COMMENTED** [review]
line183: typically advertising a fabric default route directed towards the
   superspine to southwards peer routers (children)
"superspine"  may seem not straightforward for readers to understand, change to "parents" or "ToF"?

**Comment by weiyuehua** [comment]
Line 795:  RIFT is designed to require an arch minimal configuration to simplify
   its operation and avoid human errors
What does "arch" mean here?

**Comment by weiyuehua** [comment]
L807 IOW that the SystemID of each node is unique,
I suggest expand IOW to "in other words".

**Comment by pthubert** [comment]
Will make a pull req to perform the changes

**Pull request merged**
